### ISSUE TITLE
Update Pandas Verson

### ISSUE THREAD

**Issue by uwaisiqbal** [EthicalML/xai#1]
Can you update the requirements to use the latest version of pandas? Pretty please 😺

**Comment by axsaucedo** [comment]
Hey @uwaisiqbal - for sure, this would be actually quite useful. Would you be up for submitting a PR? Definitely keen to get contributions :)

**Comment by uwaisiqbal** [comment]
I've opened up a PR with the change 💪

**Comment by axsaucedo** [comment]
Great! Thanks @uwaisiqbal - just landed 👍

**Comment by uwaisiqbal** [comment]
😎
