### ISSUE TITLE
AttributeError: module 'xai' has no attribute 'show_imbalances;

### ISSUE THREAD

**Issue by hyamychen** [EthicalML/xai#4]
AttributeError: module 'xai' has no attribute 'show_imbalances;
How to handle this error?

**Comment by catethos** [comment]
i think the function has been renamed to `imbalance_plot` in this commit: https://github.com/EthicalML/xai/commit/ac3a4117c6cf986e25941556f3de0c70e9a81c13

**Comment by axsaucedo** [comment]
That is correct, thank you @catethos - we can re-focus this issue on updating the documentation. Thanks for the heads up @hyamychen

**Comment by axsaucedo** [comment]
Fixed via #13
