### ISSUE TITLE
matplotlib error while installing package

### ISSUE THREAD

**Issue by ArpitSisodia** [EthicalML/xai#5]
Collecting matplotlib==3.0.2 

  Using cached matplotlib-3.0.2.tar.gz (36.5 MB)
    ERROR: Command errored out with exit status 1:
     command: /opt/anaconda3/envs/ethicalml/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/wv/m62_p54d5bx1dnq_m07ck3l40000gn/T/pip-install-303disb7/matplotlib/setup.py'"'"'; __file__='"'"'/private/var/folders/wv/m62_p54d5bx1dnq_m07ck3l40000gn/T/pip-install-303disb7/matplotlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/wv/m62_p54d5bx1dnq_m07ck3l40000gn/T/pip-install-303disb7/matplotlib/pip-egg-info

**Comment by americoalmeida** [comment]
I´m having the same issue

**Comment by axsaucedo** [comment]
Thank you for reporting @ArpitSisodia & @americoalmeida - I have been looking at upgrading the versions for a while but it seems there would be some nuances on doing so, if you managed to find a workaround it would be great if you could contribute upstream as a pull request

**Comment by axsaucedo** [comment]
Fixed via #13
