### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by focalfossa** [EthicalML/xai#7]
Hello!

I've been trying to install this package and am unable to do so. 
I've tried both methods on my Ubuntu machine.
1. `pip install xai`
2. `python setup.py install`

What can I do to install this?
Also, is this project active anymore at all?

**Comment by axsaucedo** [comment]
@focalfossa certainly, I just tried it locally and it was possible to install, what is the error you are getting? Can you provide details on your environment and the error output?

**Comment by focalfossa** [comment]
Never mind. It is working now. I tried installing it in a different machine in a virtual environment and it worked. Thanks though!
