### ISSUE TITLE
Can we explain BERT models using this package?

### ISSUE THREAD

**Issue by shadab-entrepreneur** [EthicalML/xai#8]
I'm working with text data and looking for ways to explain BERT models. Is there any workaround using XAI or any other package/resources if anyone can recommend?

**Comment by axsaucedo** [comment]
Currently this package doesn't support text, but there are a broad range of packages that do, we curate a list of explainability tools, so may be worth checking those out https://github.com/EthicalML/awesome-production-machine-learning/#explaining-black-box-models-and-datasets
